# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "359bf999163b1207fdadef1b92fbf132"
application_url = "https://non-embeded-shopify-app-gilt.vercel.app/"
embedded = true
name = "xml-feed-gerator-app"
handle = "xml-feed-gerator-app"

[build]
automatically_update_urls_on_dev = true
dev_store_url = "xml-feed-generator.myshopify.com"
include_config_on_deploy = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://non-embeded-shopify-app-gilt.vercel.app/auth/callback",
  "https://non-embeded-shopify-app-gilt.vercel.app/auth/shopify/callback",
  "https://non-embeded-shopify-app-gilt.vercel.app/api/auth/callback"
]

[pos]
embedded = true
