-- CreateTable
CREATE TABLE "ProductFields" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "feedName" TEXT NOT NULL,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL
);
